distributable:
  url: https://github.com/tmux/tmux/releases/download/{{version}}/tmux-{{version}}.tar.gz
  strip-components: 1

versions:
  github: tmux/tmux/tags

build:
  dependencies:
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
    libevent.org: ^2.0
    invisible-island.net/ncurses: '*'
  script: |
    ./configure $ARGS
    make
    make install
  env:
    ARGS:
      - --prefix={{prefix}}
    darwin:
      ARGS:
        - --enable-utf8proc
    linux:
      ARGS:
        - --disable-utf8proc

test:
  script: |
    tmux -V

provides:
  - bin/tmux
