distributable:
  url: https://codeload.github.com/rustls/rustls/tar.gz/refs/tags/v/{{version}}
  strip-components: 1

provides:
  - bin/rustls

versions:
  github: rustls/rustls/tags
  strip: /v\//

build:
  dependencies:
    rust-lang.org/cargo: '*'
  script: |
    cargo build --release --package rustls --lib --out-dir {{prefix}} -Z unstable-options

test:
  script: true #FIXME
