distributable:
   url: https://gitlab.com/libtiff/libtiff/-/archive/v{{version}}/libtiff-v{{version}}.tar.gz
   strip-components: 1

versions:
  - 4.5.0 # repo is on gitlab

dependencies:
  zlib.net: ^1
  libjpeg-turbo.org: ^2
  facebook.com/zstd: ^1

build:
  dependencies:
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
    cmake.org: ^3
  working-directory: out
  script: |
    cmake .. $ARGS
    make
    make install
  env:
    ARGS:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX="{{prefix}}"

provides:
  - bin/fax2ps
  - bin/fax2tiff
  - bin/pal2rgb
  - bin/ppm2tiff
  - bin/raw2tiff
  - bin/tiff2bw
  - bin/tiff2pdf
  - bin/tiff2ps
  - bin/tiff2rgba
  - bin/tiffcmp
  - bin/tiffcp
  - bin/tiffcrop
  - bin/tiffdither
  - bin/tiffdump
  - bin/tiffgt
  - bin/tiffinfo
  - bin/tiffmedian
  - bin/tiffset
  - bin/tiffsplit

test:
  dependencies:
    gnu.org/wget: '*'
  script: |
    wget https://people.math.sc.edu/Burkardt/data/tif/at3_1m4_01.tif
    tiff2pdf -o at3_1m4_01.pdf at3_1m4_01.tif 