distributable:
  url: https://github.com/joerdav/xc/archive/refs/tags/v{{ version }}.tar.gz
  strip-components: 1

versions:
  github: joerdav/xc/tags
  strip: /v /

build:
  dependencies:
    go.dev: '*'
  script: |
    cd ./cmd/xc
    GOBIN={{prefix}}/bin go install -ldflags "-X main.version={{version}}" .

test:
  xc -version

provides:
  - bin/xc


