distributable:
  url: https://github.com/AcademySoftwareFoundation/openexr/archive/refs/tags/v{{version}}.tar.gz
  strip-components: 1

versions:
  github: AcademySoftwareFoundation/openexr/tags  # reads github tags from github
  strip: /^v/

dependencies:
  zlib.net: ^1
  openexr.com/imath: '*'

build:
  dependencies:
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
    cmake.org: '*'
    freedesktop.org/pkg-config: '*'
  working-directory: build
  script: |
    cmake .. $ARGS
    make install
  env:
    ARGS:
      - -DCMAKE_INSTALL_PREFIX="{{prefix}}"
      - -DCMAKE_BUILD_TYPE=Release

provides:
  - bin/foo
  # ^^ specify the binaries or tea magic won’t work

test:
  dependencies:
    foo.com: '*'  # asterisk means “any version, usually the latest”
  script:
    test "$(foo --version)" = {{version}}
  # ^^ we prefer that you test the functionality of the package works, but
  # we know tests are tedious, so will (for now) accept a simple version check
