distributable:
  url: https://github.com/htop-dev/htop/releases/download/{{version}}/htop-{{version}}.tar.xz
  strip-components: 1

versions:
  github: htop-dev/htop/tags

dependencies:
  invisible-island.net/ncurses: 6

build:
  dependencies:
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
    gnu.org/autoconf: '*'
    gnu.org/automake: '*'
    invisible-island.net/ncurses: 6
  script: |
    ./autogen.sh && \
    ./configure --prefix={{prefix}} && \
    make
    make install
  test:
    make test


test:
  script: |
    htop -h