distributable:
   url: https://github.com/tesseract-ocr/tesseract/archive/refs/tags/{{version}}.tar.gz
   strip-components: 1

versions:
  github: tesseract-ocr/tesseract/tags

dependencies:
  foo.com: ^1.2.3

build:
  dependencies:
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
    # ^^ often packages need dependencies to build, it is very common for
    # packages to need a C compiler and make, the above provide those
  script: |
    ./configure $ARGS
    make --jobs {{ hw.concurrency }} install
  # it’s extremely common for packages to require the above

provides:
  - bin/foo
  # ^^ specify the binaries or tea magic won’t work

test:
  dependencies:
    foo.com: '*'  # asterisk means “any version, usually the latest”
  script:
    test "$(foo --version)" = {{version}}
  # ^^ we prefer that you test the functionality of the package works, but
  # we know tests are tedious, so will (for now) accept a simple version check
