distributable:
   url: https://github.com/tesseract-ocr/tesseract/archive/refs/tags/{{version}}.tar.gz
   strip-components: 1

versions:
  github: tesseract-ocr/tesseract/tags

dependencies:
  cairographics.org: 1
  unicode.org: 71
  leptonica.org: '*'
  libarchive.org: '*'
  gnome.org/pango: 1

runtime:
  env:
    TESSDATA_PREFIX: "{{prefix}}/share/tessdata/"

build:
  dependencies:
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
    gnu.org/autoconf: '*'
    gnu.org/automake: '*'
    gnu.org/libtool: '*'
    freedesktop.org/pkg-config: '*'
    gnu.org/wget: '*'
  script: |
    ./autogen.sh
    ./configure $ARGS
    make --jobs {{ hw.concurrency }} 
    make install 

    # install trained datafiles and move to share/tessdata
    wget https://github.com/tesseract-ocr/tessdata/blob/main/eng.traineddata?raw=true -O eng.traineddata
    wget https://github.com/tesseract-ocr/tessdata/blob/main/osd.traineddata?raw=true -O osd.traineddata
    mv eng.traineddata "{{prefix}}"/share/tessdata/
    mv osd.traineddata "{{prefix}}"/share/tessdata/
    
  env: 
    ARGS: 
      - --prefix="{{prefix}}"
      - --disable-dependency-tracking
      - --datarootdir="{{prefix}}"/share

provides:
  - bin/tesseract

test:
  script: |
    tesseract eurotext.png stdout -l eng
