distributable:
   url: https://git3.sh/git3.w3q/git3-cli/archive/master.tar.gz
   strip-components: 1

versions:
  - 0.1.3 # they don't have a version yet, I took the version from package.json

dependencies:
  nodejs.org: ^18

build:
  dependencies:
    classic.yarnpkg.com: '*'
    stedolan.github.io/jq: '*'
  script: |
    mkdir -p {{prefix}}/bin
    sed -i.bak 's|/usr/local/bin|{{prefix}}/bin|g' package.json
    sed -i.bak 's|wait|sleep 10|g' package.json

    # patch git3.pkg.json to add:
    # - node18-macos-arm64
    # - node18-linux-arm64
    jq \
      '.pkg.targets[3] |= . + "node18-macos-arm64" | .pkg.targets[4] |= . + "node18-linux-arm64"' \
      git3.pkg.json > git3.pkg.json.tmp
    mv git3.pkg.json.tmp git3.pkg.json
    ARCH=$(uname -m | sed -e 's/x86_64/x64/' -e 's/aarch64/arm64/')
    sed -i.bak \
      -e "s_bin/git3-macos _bin/git3-macos-${ARCH} _g" \
      -e "s_bin/git3-linux _bin/git3-linux-${ARCH} _g" \
      package.json
    grep cp\ bin/git3 package.json
    yarn
    yarn $INSTALL
  env:
    linux:
      INSTALL: install-linux
    darwin:
      INSTALL: install-mac

provides:
  - bin/git-remote-git3
  - bin/git3

test: |
  git3 --help
  git3 wallet list
