distributable:
   url: https://github.com/uclouvain/openjpeg/archive/refs/tags/v{{version}}.tar.gz
   strip-components: 1

# if there’s a github then we can parse the versions
versions:
  github: uclouvain/openjpeg/tags  # reads github tags from github
  strip: /^v/

dependencies:
  libpng.org: ^1
  simplesystems.org/libtiff: ^4
  littlecms.com: ^2

build:
  dependencies:
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
    cmake.org: ^3
    doxygen.nl: ^1
  working-directory: build
  script: |
    cmake $ARGS ..
    make --jobs {{ hw.concurrency }} 
    make install
  env: 
    ARGS:
      - -DCMAKE_INSTALL_PREFIX="{{prefix}}"
      - -DCMAKE_BUILD_TYPE=Release

provides:
  - bin/opj_compress
  - bin/opj_decompress
  - bin/opj_dump

test:
  dependencies:
    gnu.org/wget: '*'
  script: |
    wget https://people.math.sc.edu/Burkardt/data/bmp/blackbuck.bmp
    opj_compress -i blackbuck.bmp -o blackbuck.jp2