distributable:
  url: https://github.com/PRQL/prql/archive/refs/tags/{{ version }}.tar.gz
  strip-components: 1

versions:
  github: PRQL/prql/tags

build:
  dependencies:
    rust-lang.org/cargo: '*'
  script: |
    cd ./prql-compiler
    cargo install --path . --root {{prefix}}

test:
  echo "from employees | filter has_dog | select salary" | prql-compiler compile

provides:
  - bin/prql-compiler