distributable:
   url: https://github.com/facebook/zstd/releases/download/v{{version}}/zstd-{{version}}.tar.gz
   strip-components: 1

# if there’s a github then we can parse the versions
versions:
  github: facebook/zstd/tags  # reads github tags from github
  strip: /^Zstandard v/

dependencies:
  lz4.org: '*'
  tukaani.org/xz: '*'

build:
  dependencies:
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
    freedesktop.org/pkg-config: '*'
  script: |
    # ./configure $ARGS
    make --jobs {{ hw.concurrency }} PREFIX={{prefix}}
    make install PREFIX={{prefix}}
  env:
    ARGS:
      - --prefix={{prefix}}

provides:
  - bin/zstd
  - bin/zstdgrep
  - bin/zstdless


test:
  dependencies:
    gnu.org/wget: '*'
  script: |
    wget https://github.com/facebook/zstd/releases/download/v1.1.3/github_users_sample_set.tar.zst
    zstd -d github_users_sample_set.tar.zst
    tar xvf github_users_sample_set.tar
    zstd -b1 -r github

