distributable:
  url: https://github.com/krzkaczor/ny/archive/refs/tags/v{{ version }}.tar.gz
  strip-components: 1

# if there’s a github then we can parse the versions
versions:
  github: krzkaczor/ny/releases/tags

build:
  dependencies:
    rust-lang.org/cargo: '*'
  script: |
    cargo install --locked --path . --root {{prefix}}

provides:
  - bin/ny

test: |
  ny --version